# Generated by Django 5.1.6 on 2025-03-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factures',
            new_name='Facture',
        ),
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
