# Generated by Django 5.1.6 on 2025-03-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0002_rename_factures_facture_rename_produits_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='products',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='products_quantity',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FactureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.produit')),
            ],
        ),
    ]
