# Generated by Django 5.1.6 on 2025-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0004_user_email_alter_produit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
