# Generated by Django 5.1.6 on 2025-03-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0006_facture_facture_id_user_city_user_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
