# Generated by Django 5.1.6 on 2025-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0007_alter_facture_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
