# Generated by Django 5.1.6 on 2025-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0009_facture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='image',
        ),
    ]
