# Generated by Django 5.1.6 on 2025-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0010_remove_facture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total_product',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='total_quantities',
            field=models.IntegerField(null=True),
        ),
    ]
