# Étape 1 : Utiliser une image Python officielle
FROM python:3.13-slim

# Installer Tesseract OCR
RUN apt-get update && \
    apt-get install -y tesseract-ocr libgl1 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de l'app
COPY . /app

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Ouvrir le port 8000 pour le serveur de dev Django
EXPOSE 8000

# Commande pour lancer le serveur
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
